spring.datasource.url=jdbc:mysql://centerbeam.proxy.rlwy.net:52466/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=WCRebFcphpvFLOJLPRYcCZgJidPTCKYz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
